---
kind: pipeline
name: no-cache

steps:
  - name: no cache
    image: maven:3.6.3-adoptopenjdk-11
    environment:
      MAVEN_OPTS: "-Dmaven.repo.local=.m2"
    commands:
      - "mvn package"

  - name: rebuild-cache
    image: plugins/s3-cache
    settings:
      pull: true
      endpoint: http://fakes3:4567
      access_key: 1234
      secret_key: 1234
      rebuild: true
      root: fakes3
      mount:
        - .m2

  - name: cleanup
    image: maven:3.6.3-adoptopenjdk-11
    commands:
      - rm -rf .m2 && rm -rf target

  - name: restore-cache
    image: plugins/s3-cache
    settings:
      pull: true
      endpoint: http://fakes3:4567
      access_key: 1234
      secret_key: 1234
      restore: true
      root: fakes3

  - name: with cache
    image: maven:3.6.3-adoptopenjdk-11
    environment:
      MAVEN_OPTS: "-Dmaven.repo.local=.m2"
    commands:
      - "mvn package"